### ISSUE TITLE
is documentation correct ?

### ISSUE THREAD

**Issue by djleonskennedy** [osamaq/reactnative-fastlane-appcenter#1]
Hello

Documentation says that `cd YourAppName && mkdir fastlane && cd fastlane && touch Fastfile`
As i understand fastlane init have to be init in both platform specific folders: `ios` and `android`
otherwise an error will appear

Is it correct ?

Regards

**Comment by osamaqarem** [comment]
Hi there. There shouldn't be any issue. Did you face an error? Let me know more details and I'll try to help.

The commands we specify in the guide do take into account where the fastfile is located with respect to the iOS and Android folders. Therefore, as long as the relative path for the fastlane commands is correct, there should'nt be any issues. 

If you did in fact face an issue following the guide, please do let me know and I'll try to help. Thanks!

**Comment by osamaqarem** [comment]
I just took a look at the ["install fastlane"](https://github.com/osamaq/reactnative-fastlane-appcenter#requirements) step which now that I think about it, is quite ambigious.

I think I understand the confusion now. You only need to follow the [Installing fastlane](https://docs.fastlane.tools/getting-started/ios/setup/#installing-fastlane) part of the official docs, but not the [Setting up fastlane](https://docs.fastlane.tools/getting-started/ios/setup/#setting-up-fastlane) as that part is meant for purely either Android or iOS apps and not both as with React Native. 

If you want to manage your Android and iOS projects with fastlane independently, you can still do `fastlane init` inside each project folder. Following this guide, you will do what 'init' does but manually at the JS side of things.

Personally speaking, I usually have [fastlane scripts](https://github.com/osamaq/react-native-template/blob/master/template/fastlane/Fastfile) that reference files at the JS side of things (e.g. `package.json` version) and apply to both Android and iOS projects. Additionally, we can use the lanes feature of fastfiles to manage and separate things in a clear way as this guide does. With those facts in mind, it makes more sense to me to place the fastfile at the JS side of things for more convenient usage. Hope that clears things up.

I will update the guide to be more clear regarding the installation. Let me know if you have any other questions.

**Comment by djleonskennedy** [comment]
@osamaq that's clear, thank you!
