### ISSUE TITLE
Error 403: {"message"=>"Forbidden", "statusCode"=>403, "code"=>"Forbidden"} 

### ISSUE THREAD

**Issue by mainak-shil** [osamaq/reactnative-fastlane-appcenter#3]
please help!

![Screenshot 2023-12-10 at 9 21 33 PM](https://github.com/osamaqarem/reactnative-fastlane-appcenter/assets/24505861/d48f2fac-8531-4cda-9c9c-e2437403c83b)

![Screenshot 2023-12-10 at 9 38 51 PM](https://github.com/osamaqarem/reactnative-fastlane-appcenter/assets/24505861/2c15b4f9-ec0f-4e63-859d-cc8c75f0c2ab)

**Comment by osamaqarem** [comment]
hey, check out this similar issue https://github.com/microsoft/fastlane-plugin-appcenter/issues/47#issuecomment-1011772729
I would like to keep the issues on this doc related to problems with the steps specifically. I hope you can figure it out!
