### ISSUE TITLE
Suggestion: Add a License

### ISSUE THREAD

**Issue by achesin** [osamaq/reactnative-fastlane-appcenter#4]
Hi there! A lot of people use this project and I wanted to see if you were open to adding a [software license](https://en.wikipedia.org/wiki/Software_license) on this project? It would set clear boundaries for this project to be used or extended. A lot of projects on GitHub choose a license to use and here is a doc on GitHub that I've found helpful in choosing a license: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository 
Thank you for considering!

**Comment by osamaqarem** [comment]
Thanks! Added CC0.
